version: '3.8'

services:
  chit-chat:
    image: berserker619/main-api:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/chit-chat
      - PORT=3000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: